USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE ROLE AGG_ADMIN;

GRANT ROLE AGG_ADMIN TO USER JSINGH22;

CREATE OR REPLACE DATABASE PRIVACY_LAB;
CREATE OR REPLACE SCHEMA PRIVACY_LAB.POLICIES;

GRANT USAGE ON DATABASE PRIVACY_LAB TO ROLE AGG_ADMIN;
GRANT USAGE ON SCHEMA PRIVACY_LAB.POLICIES TO ROLE AGG_ADMIN;


GRANT CREATE AGGREGATION POLICY ON SCHEMA PRIVACY_LAB.POLICIES TO ROLE AGG_ADMIN;

GRANT APPLY AGGREGATION POLICY ON ACCOUNT TO ROLE AGG_ADMIN;

USE ROLE AGG_ADMIN;
USE SCHEMA PRIVACY_LAB.POLICIES;

CREATE OR REPLACE AGGREGATION POLICY p_min_group_5
as () RETURNS AGGREGATION_CONSTRAINT -> 
case when current_role() ='ACCOUNTADMIN' THEN NO_AGGREGATION_CONSTRAINT()
ELSE AGGREGATION_CONSTRAINT(MIN_GROUP_SIZE => 5)
END;


/*USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE TABLE PRIVACY_LAB.PUBLIC.SENSITIVE_ORDERS AS
sELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS LIMIT 1000;*/

USE ROLE AGG_ADMIN;

ALTER TABLE PRIVACY_LAB.PUBLIC.SENSITIVE_ORDERS 
SET AGGREGATION POLICY PRIVACY_LAB.POLICIES.P_MIN_GROUP_5;


USE ROLE DA_ANALYST;

SELECT * FROM PRIVACY_LAB.PUBLIC.SENSITIVE_ORDERS;


SELECT O_ORDERSTATUS, COUNT(*), AVG(O_TOTALPRICE)
FROM PRIVACY_LAB.PUBLIC.SENSITIVE_ORDERS
GROUP BY O_ORDERSTATUS;

SELECT O_CUSTKEY, COUNT(*), SUM(O_TOTALPRICE)
FROM PRIVACY_LAB.PUBLIC.SENSITIVE_ORDERS
GROUP BY O_CUSTKEY
HAVING COUNT(*) < 3;


SELECT * FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(
POLICY_NAME=>'PRIVACY_LAB.POLICIES.P_MIN_GROUP_5'
));


SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.AGGREGATION_POLICIES
WHERE DELETED IS NULL;









