/* CREATE DATABASE AND SCHEMA */
create or replace database LINEAGE_DB;

create or replace schema LA_SCHEMA;

USE DATABASE LINEAGE_DB;
USE SCHEMA LA_SCHEMA;

-- Example: Create some dependencies
CREATE OR REPLACE TABLE LINEAGE_DB.LA_SCHEMA.SALES (ID INT, AMOUNT NUMBER);
--level `1`
CREATE OR REPLACE VIEW LINEAGE_DB.LA_SCHEMA.SALES_VIEW AS
SELECT * FROM LINEAGE_DB.LA_SCHEMA.SALES;
--level 2
CREATE OR REPLACE VIEW LINEAGE_DB.LA_SCHEMA.SECOND_SALES_VIEW AS
SELECT * FROM LINEAGE_DB.LA_SCHEMA.SALES_VIEW;
--level 1
CREATE OR REPLACE MATERIALIZED VIEW LINEAGE_DB.LA_SCHEMA.SALES_SUMMARY AS
SELECT COUNT(*) AS CNT, SUM(AMOUNT) AS TOTAL
FROM LINEAGE_DB.LA_SCHEMA.SALES;

-- Use GET_LINEAGE to trace dependencies 
SELECT *
FROM TABLE(SNOWFLAKE.CORE.GET_LINEAGE('LINEAGE_DB.LA_SCHEMA.SALES', 'TABLE', 'DOWNSTREAM', 2));

--- Check Object Dependency

SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES
WHERE REFERENCED_OBJECT_NAME LIKE '%SALES%';