select current_ip_address();  

create or replace network rule my_id_rulee
TYPE=IPV4
MODE=INGRESS
VALUE_LIST=('')
COMMENT ='POLICY FOR DEMO'
;

CREATE OR REPLACE USER DEMO_TEST_USER
PASSWORD='1234'
DEFAULT_ROLE=PUBLIC;

CREATE OR REPLACE NETWORK POLICY DEMO_NETWORK_POLICY
ALLOWED_NETWORK_RULE_LIST=('my_id_rulee')
COMMENT=' THIS IS MY NETOWRK POLICY';


ALTER USER DEMO_TEST_USER SET NETWORK_POLICY=DEMO_NETWORK_POLICY;