USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE DATABASE GOVERNANCE;

CREATE OR REPLACE SCHEMA GOVERNANCE.TAGS;

GRANT USAGE ON DATABASE GOVERNANCE TO ROLE DA_ANALYST;


GRANT USAGE ON SCHEMA GOVERNANCE.TAGS TO ROLE DA_ANALYST;


CREATE OR REPLACE TAG GOVERNANCE.TAGS.PII_DATA
ALLOWED_VALUES 'HIGH','MEDIUM','LOW'
COMMENT='THIS IS MY TAG';

alter table analyst_db.PUBLIC.EMPLOYEES
SET TAG GOVERNANCE.TAGS.PII_DATA ='HIGH'; 

alter table analyst_db.PUBLIC.EMPLOYEES
MODIFY COLUMN EMPLOYEENAME
SET TAG GOVERNANCE.TAGS.PII_DATA ='MEDIUM'; 

SELECT *
FROM TABLE(
  information_schema.tag_references(
    'analyst_db.public.employees', 
    'table'
  )
);