USE ROLE ACCOUNTADMIN;

GRANT CREATE PROJECTION POLICY ON SCHEMA PRIVACY_LAB.POLICIES TO ROLE AGG_ADMIN;

GRANT APPLY PROJECTION POLICY ON ACCOUNT TO ROLE AGG_ADMIN;


USE ROLE AGG_ADMIN;

USE SCHEMA PRIVACY_LAB.POLICIES;

CREATE OR REPLACE PROJECTION POLICY P_HIDE_COLUMN
AS() RETURNS PROJECTION_CONSTRAINT ->
CASE WHEN CURRENT_ROLE()='ACCOUNTADMIN' THEN PROJECTION_CONSTRAINT(ALLOW=>TRUE)
ELSE PROJECTION_CONSTRAINT(ALLOW=>FALSE)
END;


USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE TABLE PRIVACY_LAB.PUBLIC.PROTECTED_CUSTOMERS
AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER LIMIT 1000;


USE ROLE AGG_ADMIN;
ALTER TABLE PRIVACY_LAB.PUBLIC.PROTECTED_CUSTOMERS 
MODIFY COLUMN C_PHONE SET PROJECTION POLICY P_HIDE_COLUMN;

ALTER TABLE PRIVACY_LAB.PUBLIC.PROTECTED_CUSTOMERS 
MODIFY COLUMN C_ACCTBAL SET PROJECTION POLICY P_HIDE_COLUMN;

USE ROLE DA_ANALYST;
SELECT * FROM PRIVACY_LAB.PUBLIC.PROTECTED_CUSTOMERS;

SELECT C_NAME, C_MKTSEGMENT, C_ADDRESS 
FROM PRIVACY_LAB.PUBLIC.PROTECTED_CUSTOMERS;



SELECT C_NAME, C_MKTSEGMENT 
FROM PRIVACY_LAB.PUBLIC.PROTECTED_CUSTOMERS
WHERE C_ACCTBAL > 5000; 


SELECT * FROM TABLE(INFORMATION_SCHEMA.POLICY_REFERENCES(POLICY_NAME => 'p_hide_column'));